import { Link, createFileRoute } from '@tanstack/react-router'
import { ArrowRight, BadgeCheck, Clock3, Gamepad2, Headphones, ShieldCheck, Sparkles, Star, Zap } from 'lucide-react'
import { ProductCard } from '@/components/ProductCard'
import { games, products, services } from '@/data/catalog'

export const Route = createFileRoute('/')({ component: HomePage })

function HomePage() {
  return <>
    <section className="hero">
      <div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-grid"/>
      <div className="hero-copy reveal"><div className="eyebrow"><span/> ELITE GAMING SERVICES</div><h1>OWN THE<br/><em>GAMEWORLD.</em></h1><p>Premium boosting, unlocks, currency, and account services — delivered by vetted gaming specialists.</p><div className="hero-actions"><Link to="/catalog" className="button primary">Explore services <ArrowRight size={18}/></Link><Link to="/info/$page" params={{page:'how-it-works'}} className="button secondary">How it works</Link></div><div className="hero-proof"><div><b>4.9</b><span><span className="stars">★★★★★</span><small>12,000+ reviews</small></span></div><div><b>150+</b><span><small>Supported games</small></span></div><div><b>24/7</b><span><small>Expert support</small></span></div></div></div>
      <div className="hero-art reveal delay-1"><div className="hero-card back"><span>ACTIVE ORDER</span><b>RANK ASCENSION</b><i>68% complete</i></div><div className="hero-card main"><div className="card-top"><span>APEX // 01</span><Gamepad2/></div><strong>CLAD<br/>GAMEWORLD</strong><p>THE PREMIUM EDGE</p><div className="scanline"/></div><div className="hero-card stat"><Zap/><span><b>2,847</b><small>orders completed this week</small></span></div></div>
      <div className="trust-strip"><span><ShieldCheck/> Buyer protection</span><span><BadgeCheck/> Vetted specialists</span><span><Clock3/> Live order tracking</span><span><Headphones/> 24/7 human support</span></div>
    </section>

    <section className="section service-section"><div className="section-heading"><div><span className="kicker">CHOOSE YOUR ADVANTAGE</span><h2>Services built to<br/><em>move you forward.</em></h2></div><Link to="/catalog">View all services <ArrowRight size={16}/></Link></div><div className="service-grid">{services.map((service, index) => <Link key={service.slug} to="/services/$serviceSlug" params={{serviceSlug:service.slug}} className={`service-card ${index === 1 ? 'featured' : ''}`}><span className="service-number">0{index + 1}</span><i>{service.icon}</i><small>{service.eyebrow}</small><h3>{service.name}</h3><p>{service.description}</p><b>Explore <ArrowRight size={15}/></b></Link>)}</div></section>

    <section className="section dark-panel"><div className="section-heading"><div><span className="kicker gold">THIS WEEK'S LOADOUT</span><h2>Featured services.</h2></div><div className="flash-pill"><span/> FLASH SALE ENDS 04:18:32</div></div><div className="product-grid">{products.slice(0,4).map((product)=><ProductCard product={product} key={product.id}/>)}</div><div className="center-action"><Link to="/catalog" className="button secondary">Browse the marketplace <ArrowRight size={17}/></Link></div></section>

    <section className="section games-section"><div className="section-heading"><div><span className="kicker">150+ WORLDS. ONE HUB.</span><h2>Find your game.</h2></div><Link to="/catalog">View complete directory <ArrowRight size={16}/></Link></div><div className="games-grid">{games.slice(0,12).map((game, index)=><Link key={game.slug} to="/games/$gameSlug" params={{gameSlug:game.slug}} className={`game-tile game-${index%6}`} style={{'--game-accent':game.accent} as React.CSSProperties}><span>{game.code}</span><div><b>{game.name}</b><small>{index%3+4} services available</small></div><ArrowRight/></Link>)}</div></section>

    <section className="steps-section"><div className="steps-intro"><span className="kicker gold">ZERO FRICTION</span><h2>From cart to<br/><em>victory.</em></h2><p>A clear, protected experience from your first click to final delivery.</p><Link to="/info/$page" params={{page:'how-it-works'}}>See how we protect every order →</Link></div><div className="steps-list">{[['01','Choose your service','Pick your game, configure the details, and get an instant price.'],['02','Checkout securely','Pay with card, PayPal, Apple Pay, Google Pay, or crypto.'],['03','Track every milestone','Message your specialist and watch progress from your dashboard.'],['04','Confirm & conquer','Review the delivery, approve the order, and get back in the game.']].map(([number,title,copy])=><div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>

    <section className="section testimonial-section"><div className="testimonial-score"><span className="kicker">PLAYER APPROVED</span><strong>4.9<small>/5</small></strong><div className="stars">★★★★★</div><p>Based on 12,000+ verified orders</p></div><div className="testimonial"><Star fill="currentColor"/><blockquote>“The experience felt more professional than any gaming marketplace I’ve used. Updates were constant, delivery was early, and support answered in under a minute.”</blockquote><div><span className="avatar">JM</span><p><b>Jordan M.</b><small>Verified GTA V customer</small></p><BadgeCheck/></div></div><div className="testimonial mini"><Sparkles/><blockquote>“Clean, fast, and exactly as ordered.”</blockquote><div><span className="avatar">AK</span><p><b>Alex K.</b><small>Verified WoW customer</small></p></div></div></section>

    <section className="final-cta"><div><span className="kicker gold">YOUR NEXT LEVEL STARTS HERE</span><h2>Ready to change<br/>the way you play?</h2><p>Join thousands of players who choose Apex Gaming Hub for premium service without the uncertainty.</p><Link to="/catalog" className="button primary">Enter the marketplace <ArrowRight/></Link></div><div className="cta-emblem"><span>ADME</span><small>APEX GAMING HUB</small></div></section>
  </>
}
