import { createFileRoute } from '@tanstack/react-router'
import { Mail, MessageSquare, ShieldCheck } from 'lucide-react'
const pages:Record<string,{title:string;kicker:string;intro:string;sections:[string,string][]}>={
  'how-it-works':{title:'How it works.',kicker:'CLEAR FROM CLICK TO COMPLETION',intro:'A premium service experience designed around transparency, protection, and live communication.',sections:[['1. Configure your order','Choose a game, service, platform, and delivery speed. Your price updates before checkout.'],['2. Pay securely','Complete checkout through a supported payment provider. Your order is confirmed instantly.'],['3. Meet your specialist','A vetted specialist joins your private order room and confirms the delivery plan.'],['4. Track and approve','Follow progress milestones, review delivery, and confirm when everything meets your order.']]},
  faq:{title:'Frequently asked questions.',kicker:'THE ANSWERS YOU NEED',intro:'Quick answers about orders, payments, security, delivery, and support.',sections:[['Are payments secure?','Payments are processed by established payment providers. Apex Gaming Hub never stores raw card details.'],['How do I track an order?','Guest and registered customers receive an order link. Account holders also see every order in their dashboard.'],['Can I cancel an order?','Eligible orders can be cancelled before fulfillment begins. See the refund policy for full terms.'],['Which games are supported?','The marketplace includes more than 150 games, with new titles and services added regularly.']]},
  terms:{title:'Terms of service.',kicker:'LAST UPDATED AUGUST 6, 2026',intro:'These terms explain the rules for accessing and using the Apex Gaming Hub marketplace.',sections:[['Marketplace services','Service descriptions, timing, eligibility, and customer requirements are shown before checkout.'],['Customer responsibilities','Customers must provide accurate order information and maintain access to required communication channels.'],['Acceptable use','The marketplace may not be used for unlawful activity, fraud, harassment, or unauthorized resale.'],['Service limitations','Game publishers are independent third parties. Customers remain responsible for understanding applicable game terms.']]},
  privacy:{title:'Privacy policy.',kicker:'YOUR DATA, TREATED WITH CARE',intro:'This policy describes how account, order, payment, and support information is handled.',sections:[['Information collected','We collect the information needed to provide accounts, fulfill orders, process payments, and respond to support.'],['How information is used','Data supports service delivery, fraud prevention, customer communication, analytics, and legal compliance.'],['Payment privacy','Payment details are handled by payment providers and are not stored directly by the marketplace.'],['Your choices','You may request access, correction, or deletion of eligible personal information through support.']]},
  refunds:{title:'Refund policy.',kicker:'FAIR, CLEAR, PROTECTED',intro:'Our buyer protection process is designed to resolve eligible delivery issues quickly and fairly.',sections:[['Before fulfillment','Orders cancelled before a specialist starts are generally eligible for a refund to the original payment method.'],['After fulfillment starts','Completed work and delivered digital goods are not normally refundable. Partial resolutions may apply to incomplete delivery.'],['How to request help','Open a support ticket from the order room within seven days of delivery and include the relevant order details.'],['Processing times','Approved refunds are initiated promptly, while bank or payment-provider posting times may vary.']]},
}
export const Route=createFileRoute('/info/$page')({component:InfoPage})
function InfoPage(){const {page}=Route.useParams();if(page==='contact')return <div className="inner-page"><section className="page-hero compact"><span className="kicker">24/7 PLAYER SUPPORT</span><h1>We're in your corner.</h1><p>Get fast help before, during, or after your order.</p></section><section className="contact-grid"><div><MessageSquare/><h2>Live chat</h2><p>Average response under two minutes.</p><button className="button primary">Start live chat</button></div><div><Mail/><h2>Email support</h2><p>Best for detailed account and billing questions.</p><a className="button secondary" href="mailto:support@example.com">Send email</a></div><div><ShieldCheck/><h2>Order issue</h2><p>Open a protected case from your dashboard.</p><button className="button secondary">Open ticket</button></div></section></div>;const content=pages[page]||pages.faq;return <div className="inner-page legal-page"><section className="page-hero compact"><span className="kicker">{content.kicker}</span><h1>{content.title}</h1><p>{content.intro}</p></section><section className="legal-content">{content.sections.map(([title,copy])=><article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</section></div>}
