import { boolean, integer, numeric, pgEnum, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const orderStatus = pgEnum('order_status', ['pending', 'paid', 'assigned', 'in_progress', 'review', 'completed', 'cancelled', 'refunded'])
export const ticketStatus = pgEnum('ticket_status', ['open', 'waiting', 'resolved'])

export const users = pgTable('users', {
  id: serial('id').primaryKey(), email: text('email').notNull().unique(), name: text('name'), role: text('role').notNull().default('customer'), createdAt: timestamp('created_at').notNull().defaultNow(),
})
export const categories = pgTable('categories', { id: serial('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), description: text('description'), featured: boolean('featured').notNull().default(false) })
export const games = pgTable('games', { id: serial('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), accent: text('accent'), active: boolean('active').notNull().default(true) })
export const products = pgTable('products', { id: serial('id').primaryKey(), gameId: integer('game_id').references(() => games.id), categoryId: integer('category_id').references(() => categories.id), name: text('name').notNull(), slug: text('slug').notNull().unique(), description: text('description').notNull(), price: numeric('price', { precision: 10, scale: 2 }).notNull(), compareAtPrice: numeric('compare_at_price', { precision: 10, scale: 2 }), deliveryEstimate: text('delivery_estimate'), imageUrl: text('image_url'), featured: boolean('featured').notNull().default(false), active: boolean('active').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const orders = pgTable('orders', { id: serial('id').primaryKey(), orderNumber: text('order_number').notNull().unique(), userId: integer('user_id').references(() => users.id), guestEmail: text('guest_email'), status: orderStatus('status').notNull().default('pending'), subtotal: numeric('subtotal', { precision: 10, scale: 2 }).notNull(), tax: numeric('tax', { precision: 10, scale: 2 }).notNull().default('0'), total: numeric('total', { precision: 10, scale: 2 }).notNull(), paymentProvider: text('payment_provider'), paymentReference: text('payment_reference'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const orderItems = pgTable('order_items', { id: serial('id').primaryKey(), orderId: integer('order_id').notNull().references(() => orders.id), productId: integer('product_id').notNull().references(() => products.id), quantity: integer('quantity').notNull().default(1), unitPrice: numeric('unit_price', { precision: 10, scale: 2 }).notNull(), configuration: text('configuration') })
export const coupons = pgTable('coupons', { id: serial('id').primaryKey(), code: text('code').notNull().unique(), percentOff: integer('percent_off'), amountOff: numeric('amount_off', { precision: 10, scale: 2 }), active: boolean('active').notNull().default(true), expiresAt: timestamp('expires_at') })
export const reviews = pgTable('reviews', { id: serial('id').primaryKey(), productId: integer('product_id').notNull().references(() => products.id), userId: integer('user_id').references(() => users.id), rating: integer('rating').notNull(), title: text('title'), body: text('body'), approved: boolean('approved').notNull().default(false), createdAt: timestamp('created_at').notNull().defaultNow() })
export const wishlists = pgTable('wishlists', { id: serial('id').primaryKey(), userId: integer('user_id').notNull().references(() => users.id), productId: integer('product_id').notNull().references(() => products.id), createdAt: timestamp('created_at').notNull().defaultNow() })
export const supportTickets = pgTable('support_tickets', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id), orderId: integer('order_id').references(() => orders.id), subject: text('subject').notNull(), message: text('message').notNull(), status: ticketStatus('status').notNull().default('open'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const banners = pgTable('banners', { id: serial('id').primaryKey(), title: text('title').notNull(), imageUrl: text('image_url'), linkUrl: text('link_url'), active: boolean('active').notNull().default(true), startsAt: timestamp('starts_at'), endsAt: timestamp('ends_at') })
